blog_comment:
    resource: "@BlogBundle/Controller/CommentController.php"
    type:     annotation

blog_post:
    resource: "@BlogBundle/Controller/PostController.php"
    type:     annotation

blog_blog:
    resource: "@BlogBundle/Controller/BlogController.php"
    type:     annotation

blog_blog:
    resource: "@BlogBundle/Controller/BlogController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

notification:
    resource: "@NotificationBundle/Controller/"
    type:     annotation
    prefix:   /

blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
